---
apiVersion: v2
name: workload-cluster
description: An umbrella chart for a workload (k8s) cluster.
type: application
version: 0.10.4
dependencies:
- name: cluster
  version: 0.11.1
  repository: oci://ghcr.io/unbyte-de/cluster-api-cluster-charts
  import-values:
  - data
