---
cluster:
  name: "unbyte-hcloud-fsn1-linting-01"

hCloud:
  networking:
    servicesIpv4Cidr: "10.3.8.0/21"
    podsIpv4Cidr: "10.3.16.0/20"
    region: "fsn1"
  machines:
    cp:
      type: "cpx32"
      # osVersion: "2404"
      # k8sVersion: "v1.31.4"
      buildTimestamp: "1744781328"
      # replicas: 3
    workers:
      defaults:
        type: "cpx42"
        # osVersion: "2404"
        # k8sVersion: "v1.31.4"
        buildTimestamp: "1744781328"
        # replicas: 3
        replicas: 7
        autoscaler:
          # minSize: "3"
          # maxSize: "4"
          minSize: "7"
          maxSize: "9"
      pools:
        gpu:
          type: "x"
          placementGroupName: worker-gpu
          osVersion: "2404"
          k8sVersion: "v1.32.4"
          buildTimestamp: "123456"
          imageName: >-
            {{- $machines := (include "machines" $) | fromYaml -}}
            cluster-api-ubuntu-{{ $machines.workers.pools.gpu.osVersion }}-{{ $machines.workers.pools.gpu.k8sVersion }}-{{ $machines.workers.pools.gpu.buildTimestamp | required "ERROR: worker image buildTimestamp is required." }}
          replicas: 1
          autoscaler:
            enabled: true
            minSize: "1"
            maxSize: "2"

install:
  # enabled: false
  # # deleteAll: true
  envName: dev
  orgName: pbm # or unbyte
