{{- define "cluster.machine-health-checks" -}}
{{- $machines := (include "machines" .) | fromYaml }}
{{- if $machines.cp.healthCheck.enabled }}
{{- if and (eq .Values.capi.providers.infrastructure.name "hetzner") $machines.cp.remediation.enabled }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudRemediationTemplate
metadata:
  name: cp-remediation
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  template:
    spec:
      strategy:
        retryLimit: {{ $machines.cp.remediation.retryLimit }}
        timeout: {{ $machines.cp.remediation.timeout }}
        type: {{ $machines.cp.remediation.type }}
{{- end }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "cp-name" . }}-unhealthy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
spec:
  clusterName: {{ include "cluster-name" . }}
  maxUnhealthy: {{ $machines.cp.healthCheck.maxUnhealthy }}
  nodeStartupTimeout: {{ $machines.cp.healthCheck.nodeStartupTimeout }}
  {{- if $machines.cp.remediation.enabled }}
  remediationTemplate:
    {{- if eq .Values.capi.providers.infrastructure.name "hetzner" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudRemediationTemplate
    {{- end }}
    name: cp-remediation
  {{- end }}
  selector:
    matchLabels:
      cluster.x-k8s.io/control-plane: ""
  unhealthyConditions: {{- $machines.cp.healthCheck.unhealthyConditions | toYaml | nindent 2 }}
{{- end }}
{{- /* Worker nodes */}}
{{- $root := . }}
{{- $workerPools := (include "cluster.workerPools" .) | fromYaml }}
{{- range $poolName, $poolSpec := $workerPools }}
{{- $ctx := dict "root" $root "poolName" $poolName "poolSpec" $poolSpec }}
{{- $remediationName := "" }}
{{- if eq $poolName "default" -}}{{- $remediationName = "worker-remediation" -}}{{- else -}}{{- $remediationName = printf "worker-%s-remediation" $poolName -}}{{- end }}
{{- if $poolSpec.healthCheck.enabled }}
{{- if and (eq $root.Values.capi.providers.infrastructure.name "hetzner") $poolSpec.remediation.enabled }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudRemediationTemplate
metadata:
  name: {{ $remediationName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "cluster.labels" $root | nindent 4 }}
spec:
  template:
    spec:
      strategy:
        retryLimit: {{ $poolSpec.remediation.retryLimit }}
        timeout: {{ $poolSpec.remediation.timeout }}
        type: {{ $poolSpec.remediation.type }}
{{- end }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "worker-pool-name" $ctx }}-unhealthy
  namespace: {{ $root.Release.Namespace }}
  # annotations:
  #   argocd.argoproj.io/sync-wave: ""
  labels:
    {{- include "cluster.labels" $root | nindent 4 }}
spec:
  clusterName: {{ include "cluster-name" $root }}
  maxUnhealthy: {{ $poolSpec.healthCheck.maxUnhealthy }}
  nodeStartupTimeout: {{ $poolSpec.healthCheck.nodeStartupTimeout }}
  {{- if $poolSpec.remediation.enabled }}
  remediationTemplate:
    {{- if eq $root.Values.capi.providers.infrastructure.name "hetzner" }}
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudRemediationTemplate
    {{- end }}
    name: {{ $remediationName }}
  {{- end }}
  selector:
    matchLabels:
      nodepool: {{ include "worker-pool-name" $ctx }}
  unhealthyConditions: {{- $poolSpec.healthCheck.unhealthyConditions | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end -}}
