{{- define "cluster.worker-nodes" -}}
{{- $root := . }}
{{- $networking := (include "networking" .) | fromYaml }}
{{- $workerPools := (include "cluster.workerPools" .) | fromYaml }}
{{- range $poolName, $poolSpec := $workerPools }}
{{- $ctx := dict "root" $root "poolName" $poolName "poolSpec" $poolSpec }}
{{- if eq $root.Values.capi.providers.infrastructure.name "hetzner" }}
---
{{/*
https://syself.com/docs/caph/reference/hcloud-machine-template
*/}}
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "worker-hcloud-machine-template-name" $ctx }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "cluster.labels" $root | nindent 4 }}
    {{- include "worker-hcloud-machine-template-labels" $ctx | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  template:
    spec: {{- include "worker-hcloud-machine-template-spec" $ctx | nindent 6 }}
{{- end }}
{{- if eq $root.Values.capi.providers.bootstrap.name "kubeadm" }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ include "worker-kubeadm-config-template-name" $ctx }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "cluster.labels" $root | nindent 4 }}
spec:
  template:
    {{- /*
    # https://cluster-api.sigs.k8s.io/tasks/bootstrap/kubeadm-bootstrap/#kubeadmconfig-objects
    # https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/
    # k explain KubeadmConfigTemplate.spec.template.spec
    # NOTE: KubeadmConfigTemplate.spec.template.spec = KubeadmControlPlane.spec.kubeadmConfigSpec
    */}}
    spec: {{- include "worker-kubeadm-config-template-spec" $ctx | nindent 6 }}
{{- end }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "worker-pool-name" $ctx }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    nodepool: {{ include "worker-pool-name" $ctx }}
    {{- include "cluster.labels" $root | nindent 4 }}
  {{- if $poolSpec.autoscaler.enabled }}
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-enabled: "true"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ $poolSpec.autoscaler.minSize }}"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ $poolSpec.autoscaler.maxSize }}"
  {{- end }}
spec:
  clusterName: {{ include "cluster-name" $root }}
  replicas: {{ $poolSpec.replicas }}
  selector:
    matchLabels:
      nodepool: {{ include "worker-pool-name" $ctx }}
      # cluster.x-k8s.io/cluster-name: {{ include "cluster-name" $root }}
  {{- /*
  # strategy:
  #   remediation:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     deletePolicy:
  #     maxSurge:
  #     maxUnavailable:
  */}}
  template:
    metadata:
      labels:
        nodepool: {{ include "worker-pool-name" $ctx }}
        # cluster.x-k8s.io/cluster-name: {{ include "cluster-name" $root }}
    spec:
      bootstrap:
        configRef:
          {{- if eq $root.Values.capi.providers.bootstrap.name "kubeadm" }}
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "worker-kubeadm-config-template-name" $ctx }}
          {{- end }}
          namespace: {{ $root.Release.Namespace }}
      clusterName: {{ include "cluster-name" $root }}
      failureDomain: {{ $networking.region | required "ERROR: networking region is required." }}
      infrastructureRef:
        {{- if eq $root.Values.capi.providers.infrastructure.name "hetzner" }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        {{- end }}
        name: {{ include "worker-hcloud-machine-template-name" $ctx }}
        namespace: {{ $root.Release.Namespace }}
      version: {{ $poolSpec.k8sVersion | required (printf "ERROR: worker pool %q k8sVersion is required" $poolName) }}
{{- end }}
{{- end -}}
